### ISSUE TITLE
Homepage scroll to see the portfolio does not work on initial load

### ISSUE THREAD

**Issue by Llacoste2000** [marchantweb/Marchant-Web#1]
When loading the site on the homepage (first load), the scroll feature to navigate to your portfolio ends up in a blank page with only your animated background.

Here are the errors in the console : 
<img width="492" alt="image" src="https://github.com/marchantweb/Marchant-Web/assets/25367220/749c2a03-8443-4863-b6f1-b4c089fba2ee">

Steps to reproduce : 
1 - Trigger a first load on the home page (F5 on https://marchantweb.com/)
2 - Scroll to navigate to the portfolio

**Comment by marchantweb** [comment]
Thanks for the bug report. I did actually notice this once or twice, but it was sporadic. Will look into it more.

**Comment by Llacoste2000** [comment]
No problem. 
Your portfolio is amazing by the way!

**Comment by marchantweb** [comment]
After a little review, all that was happening was that the wheel scroll event on the homepage would call the `navigate` method too many times sequentially. Limiting the action to a one-time event resolves the issue. Thanks :)
